# Generated by Django 6.0.1 on 2026-02-26 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='external_company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='external_position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='jobs.jobposting'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('viewed', 'Viewed'), ('screening', 'Screening'), ('interviewing', 'Interviewing'), ('offer', 'Offer Received'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20),
        ),
    ]
