# Generated by Django 6.0.1 on 2026-01-15 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('career', '0002_initial'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedresource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercheckpointattempt',
            name='checkpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.knowledgecheckpoint'),
        ),
        migrations.AddField(
            model_name='usercheckpointattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlearningpathenrollment',
            name='current_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='learning.learningphase'),
        ),
        migrations.AddField(
            model_name='userlearningpathenrollment',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning.learningpath'),
        ),
        migrations.AddField(
            model_name='userlearningpathenrollment',
            name='personalized_for_career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personalized_enrollments', to='career.careerpath'),
        ),
        migrations.AddField(
            model_name='userlearningpathenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercheckpointattempt',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_attempts', to='learning.userlearningpathenrollment'),
        ),
        migrations.AddField(
            model_name='userresourceprogress',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_progress', to='learning.userlearningpathenrollment'),
        ),
        migrations.AddField(
            model_name='userresourceprogress',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.learningresource'),
        ),
        migrations.AddField(
            model_name='userresourceprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['slug'], name='learning_le_slug_967d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['difficulty'], name='learning_le_difficu_38b8c9_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['category'], name='learning_le_categor_cf3722_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['is_published', 'is_featured'], name='learning_le_is_publ_1f6f98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='learningphase',
            unique_together={('learning_path', 'order')},
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['resource_type'], name='learning_le_resourc_8cb70c_idx'),
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['provider'], name='learning_le_provide_80dac0_idx'),
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['is_free'], name='learning_le_is_free_b98264_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendedresource',
            unique_together={('user', 'resource')},
        ),
        migrations.AddIndex(
            model_name='userlearningpathenrollment',
            index=models.Index(fields=['user', 'status'], name='learning_us_user_id_1356fc_idx'),
        ),
        migrations.AddIndex(
            model_name='userlearningpathenrollment',
            index=models.Index(fields=['learning_path', 'status'], name='learning_us_learnin_423236_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlearningpathenrollment',
            unique_together={('user', 'learning_path')},
        ),
        migrations.AlterUniqueTogether(
            name='userresourceprogress',
            unique_together={('user', 'resource')},
        ),
    ]
