# Generated by Django 6.0.1 on 2026-01-19 17:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPathUpdate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_type', models.CharField(choices=[('injection_added', 'Remedial Content Added'), ('difficulty_adjusted', 'Difficulty Adjusted'), ('resource_replaced', 'Resource Replaced'), ('phase_reordered', 'Phase Order Changed'), ('skill_focus_changed', 'Skill Focus Updated'), ('timeline_extended', 'Timeline Extended'), ('advanced_content', 'Advanced Content Unlocked')], max_length=30)),
                ('description', models.TextField()),
                ('trigger_source', models.CharField(max_length=50)),
                ('trigger_data', models.JSONField(blank=True, default=dict)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_updates', to='learning.userlearningpathenrollment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhaseInjection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('injection_type', models.CharField(choices=[('remedial', 'Remedial (Fill knowledge gaps)'), ('reinforcement', 'Reinforcement (Practice weak areas)'), ('advanced', 'Advanced (Extra challenge)'), ('practical', 'Practical (Hands-on project)'), ('refresher', 'Refresher (Skill decay prevention)')], default='remedial', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('weak_concepts', models.JSONField(blank=True, default=list)),
                ('injected_resources', models.JSONField(blank=True, default=list)),
                ('verification_quiz', models.JSONField(blank=True, default=dict)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_score', models.PositiveIntegerField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_injections', to='learning.userlearningpathenrollment')),
                ('target_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injections', to='learning.learningphase')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSkillMastery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100)),
                ('mastery_score', models.PositiveIntegerField(default=0)),
                ('mastery_level', models.CharField(choices=[('novice', 'Novice (0-20%)'), ('beginner', 'Beginner (21-40%)'), ('intermediate', 'Intermediate (41-60%)'), ('proficient', 'Proficient (61-80%)'), ('expert', 'Expert (81-100%)')], default='novice', max_length=20)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_count', models.PositiveIntegerField(default=0)),
                ('verification_history', models.JSONField(blank=True, default=list)),
                ('decay_rate', models.FloatField(default=0.5)),
                ('days_since_practice', models.PositiveIntegerField(default=0)),
                ('learned_from', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_masteries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-mastery_score', 'skill_name'],
            },
        ),
        migrations.CreateModel(
            name='SkillRefresherQuiz',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100)),
                ('questions', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to User'), ('completed', 'Completed'), ('expired', 'Expired'), ('skipped', 'Skipped by User')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('mastery_before', models.PositiveIntegerField(default=0)),
                ('mastery_after', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresher_quizzes', to=settings.AUTH_USER_MODEL)),
                ('skill_mastery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresher_quizzes', to='learning.userskillmastery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateVerification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_url', models.URLField(blank=True)),
                ('certificate_image', models.URLField(blank=True)),
                ('course_name', models.CharField(max_length=300)),
                ('platform', models.CharField(max_length=100)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('certificate_id', models.CharField(blank=True, max_length=100)),
                ('skills_covered', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('manual_review', 'Manual Review Required')], default='pending', max_length=20)),
                ('verification_method', models.CharField(blank=True, choices=[('ocr', 'OCR Extraction'), ('api', 'Platform API'), ('manual', 'Manual Verification'), ('url_check', 'URL Verification')], max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ocr_extracted_data', models.JSONField(blank=True, default=dict)),
                ('verification_notes', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_verifications', to='learning.userlearningpathenrollment')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_verifications', to='learning.learningresource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='learning_ce_user_id_a94064_idx'), models.Index(fields=['platform'], name='learning_ce_platfor_310cbf_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project_url', models.URLField()),
                ('live_demo_url', models.URLField(blank=True)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('skills_demonstrated', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('needs_revision', 'Needs Revision'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('ai_review', models.JSONField(blank=True, default=dict)),
                ('overall_score', models.PositiveIntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to='learning.userlearningpathenrollment')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to='learning.learningphase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='learning_pr_user_id_0e7e81_idx'), models.Index(fields=['phase', 'status'], name='learning_pr_phase_i_126e93_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='userskillmastery',
            index=models.Index(fields=['user', 'skill_name'], name='learning_us_user_id_71cbcd_idx'),
        ),
        migrations.AddIndex(
            model_name='userskillmastery',
            index=models.Index(fields=['mastery_level'], name='learning_us_mastery_993858_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userskillmastery',
            unique_together={('user', 'skill_name')},
        ),
    ]
