# Generated by Django 6.0.1 on 2026-02-23 18:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_adaptive_learning_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTutorialCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('skill_name', models.CharField(max_length=100)),
                ('level', models.CharField(default='beginner', max_length=20)),
                ('ordered_video_ids', models.JSONField(default=list)),
                ('learning_tips', models.JSONField(default=list)),
                ('prerequisite_topics', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Skill Tutorial Cache',
                'unique_together': {('skill_name', 'level')},
            },
        ),
        migrations.CreateModel(
            name='UserLearningStreak',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('total_active_days', models.PositiveIntegerField(default=0)),
                ('streak_history', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Learning Streak',
            },
        ),
    ]
