# Generated by Django 6.0.1 on 2026-02-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_skilltutorialcache_userlearningstreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='generation_context',
            field=models.JSONField(blank=True, default=dict, help_text='Full user context snapshot captured at generation time'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='raw_llm_response',
            field=models.TextField(blank=True, help_text='Raw JSON string returned by the LLM — saved immediately before any DB processing'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='skill_gap_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Skill gap analysis used to construct this path'),
        ),
        migrations.AddField(
            model_name='learningphase',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='learningphase',
            name='learning_objectives',
            field=models.JSONField(blank=True, default=list, help_text='What the learner will be able to do after completing this phase'),
        ),
        migrations.AddField(
            model_name='learningphase',
            name='prerequisite_skills',
            field=models.JSONField(blank=True, default=list, help_text='Skills or knowledge required before starting this phase'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='search_query',
            field=models.CharField(blank=True, help_text='Search query to locate this resource on the provider platform', max_length=300),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
