# Generated by Django 6.0.1 on 2026-02-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_learningpath_generation_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningphase',
            name='capstone_project',
            field=models.JSONField(blank=True, default=dict, help_text='Capstone project details: title, description, deliverables, skills_demonstrated, github_search_query'),
        ),
        migrations.AddField(
            model_name='learningphase',
            name='external_topics',
            field=models.JSONField(blank=True, default=list, help_text='List of {site, topic} pairs used to build site-specific Google search links'),
        ),
        migrations.AddField(
            model_name='learningphase',
            name='recommended_certifications',
            field=models.JSONField(blank=True, default=list, help_text='List of certs: name, platform, search_query, is_free, relevance'),
        ),
        migrations.AddField(
            model_name='learningphase',
            name='youtube_queries',
            field=models.JSONField(blank=True, default=list, help_text='YouTube search queries to fetch relevant tutorial videos for this phase'),
        ),
    ]
