# Generated by Django 6.0.1 on 2026-02-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_add_phase_rich_content_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningphase',
            name='deep_dive_content',
            field=models.JSONField(blank=True, default=dict, help_text='Lazily-generated deep-dive curriculum for this phase (topics, projects, interview Q&A, etc.)'),
        ),
        migrations.AddField(
            model_name='learningphase',
            name='deep_dive_generated_at',
            field=models.DateTimeField(blank=True, help_text='When deep_dive_content was last generated — used for cache invalidation', null=True),
        ),
        migrations.AddField(
            model_name='learningphase',
            name='interview_questions',
            field=models.JSONField(blank=True, default=list, help_text='List of {question, answer, difficulty} objects for interview prep'),
        ),
        migrations.AddField(
            model_name='learningphase',
            name='phase_outcome',
            field=models.CharField(blank=True, help_text='Career-impact summary: what doing this phase unlocks for the learner', max_length=400),
        ),
        migrations.AddField(
            model_name='learningphase',
            name='readiness_checklist',
            field=models.JSONField(blank=True, default=list, help_text='Checklist of conditions that indicate readiness to proceed to next phase'),
        ),
        migrations.AddField(
            model_name='learningphase',
            name='topics_covered',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of core topics covered in this phase'),
        ),
    ]
