# Generated by Django 6.0.1 on 2026-03-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_retention_quiz_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='retentionquizattempt',
            new_name='learning_re_user_id_48194c_idx',
            old_name='learning_ret_user_id_8e4f8f_idx',
        ),
        migrations.RenameIndex(
            model_name='retentionquizattempt',
            new_name='learning_re_enrollm_f6d3c3_idx',
            old_name='learning_ret_enrollm_045994_idx',
        ),
        migrations.RenameIndex(
            model_name='retentionquizquestion',
            new_name='learning_re_is_acti_e7fffd_idx',
            old_name='learning_ret_is_acti_fca221_idx',
        ),
        migrations.RenameIndex(
            model_name='retentionquizquestion',
            new_name='learning_re_topic_871f6b_idx',
            old_name='learning_ret_topic_9117f1_idx',
        ),
        migrations.AlterField(
            model_name='retentionquizattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='retentionquizattempt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='retentionquizquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='retentionquizquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
    ]
