# Generated by Django 6.0.1 on 2026-01-15 20:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('rollout_percentage', models.IntegerField(default=0, help_text='Percentage of users (0-100) to enable for')),
            ],
            options={
                'db_table': 'feature_flags',
            },
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('endpoint', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('response_time_ms', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_usage_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='api_usage_l_user_id_cf5f1e_idx'), models.Index(fields=['endpoint', 'created_at'], name='api_usage_l_endpoin_b0dfcd_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, db_index=True, help_text='ID of the user who performed the action', null=True)),
                ('action', models.CharField(db_index=True, help_text='Type of action performed', max_length=255)),
                ('resource_type', models.CharField(blank=True, db_index=True, help_text='Type of resource affected', max_length=100, null=True)),
                ('resource_id', models.UUIDField(blank=True, help_text='ID of the resource affected', null=True)),
                ('changes', models.JSONField(blank=True, help_text='JSON object containing the changes made', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string of the request', null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='audit_log_user_id_3b54b4_idx'), models.Index(fields=['action', 'created_at'], name='audit_log_action_97df64_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_log_resourc_2570dd_idx')],
            },
        ),
    ]
