# Generated by Django 6.0.1 on 2026-01-15 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercertification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usereducation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userexperience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='interest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to='profile.interest'),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlanguage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userproject',
            name='related_experience',
            field=models.ForeignKey(blank=True, help_text='Associated work experience', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='profile.userexperience'),
        ),
        migrations.AddField(
            model_name='userproject',
            name='related_skills',
            field=models.ManyToManyField(blank=True, help_text='Skills demonstrated in this project', related_name='projects', to='profile.skill'),
        ),
        migrations.AddField(
            model_name='userproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='profile.skill'),
        ),
        migrations.AddField(
            model_name='userskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersociallink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='interest',
            index=models.Index(fields=['category', 'name'], name='interests_categor_eab6b3_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category', 'name'], name='skills_categor_e28eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['-popularity_score'], name='skills_popular_d251c5_idx'),
        ),
        migrations.AddIndex(
            model_name='usercertification',
            index=models.Index(fields=['user', '-issue_date'], name='user_certif_user_id_bfda33_idx'),
        ),
        migrations.AddIndex(
            model_name='usercertification',
            index=models.Index(fields=['issuing_organization'], name='user_certif_issuing_840d94_idx'),
        ),
        migrations.AddIndex(
            model_name='usereducation',
            index=models.Index(fields=['user', '-end_date'], name='user_educat_user_id_776201_idx'),
        ),
        migrations.AddIndex(
            model_name='usereducation',
            index=models.Index(fields=['degree_type'], name='user_educat_degree__afb142_idx'),
        ),
        migrations.AddIndex(
            model_name='usereducation',
            index=models.Index(fields=['field_of_study'], name='user_educat_field_o_cc38eb_idx'),
        ),
        migrations.AddIndex(
            model_name='userexperience',
            index=models.Index(fields=['user', '-end_date'], name='user_experi_user_id_a833ff_idx'),
        ),
        migrations.AddIndex(
            model_name='userexperience',
            index=models.Index(fields=['job_title'], name='user_experi_job_tit_411342_idx'),
        ),
        migrations.AddIndex(
            model_name='userexperience',
            index=models.Index(fields=['company_name'], name='user_experi_company_6baab9_idx'),
        ),
        migrations.AddIndex(
            model_name='userexperience',
            index=models.Index(fields=['employment_type'], name='user_experi_employm_cb3807_idx'),
        ),
        migrations.AddIndex(
            model_name='userinterest',
            index=models.Index(fields=['user', '-interest_level'], name='user_intere_user_id_c0e45d_idx'),
        ),
        migrations.AddIndex(
            model_name='userinterest',
            index=models.Index(fields=['interest'], name='user_intere_interes_9d5382_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userinterest',
            unique_together={('user', 'interest')},
        ),
        migrations.AddIndex(
            model_name='userlanguage',
            index=models.Index(fields=['user'], name='user_langua_user_id_99b3c1_idx'),
        ),
        migrations.AddIndex(
            model_name='userlanguage',
            index=models.Index(fields=['language_code'], name='user_langua_languag_9a7967_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlanguage',
            unique_together={('user', 'language_code')},
        ),
        migrations.AddIndex(
            model_name='userproject',
            index=models.Index(fields=['user', '-end_date'], name='user_projec_user_id_88d775_idx'),
        ),
        migrations.AddIndex(
            model_name='userproject',
            index=models.Index(fields=['status'], name='user_projec_status_b0a320_idx'),
        ),
        migrations.AddIndex(
            model_name='userproject',
            index=models.Index(fields=['is_featured'], name='user_projec_is_feat_39903e_idx'),
        ),
        migrations.AddIndex(
            model_name='userskill',
            index=models.Index(fields=['user', '-proficiency_level'], name='user_skills_user_id_f2c4c8_idx'),
        ),
        migrations.AddIndex(
            model_name='userskill',
            index=models.Index(fields=['skill', '-proficiency_level'], name='user_skills_skill_i_b17822_idx'),
        ),
        migrations.AddIndex(
            model_name='userskill',
            index=models.Index(fields=['source'], name='user_skills_source_8792d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('user', 'skill')},
        ),
        migrations.AddIndex(
            model_name='usersociallink',
            index=models.Index(fields=['user', 'platform'], name='user_social_user_id_8dfd6a_idx'),
        ),
    ]
