# Generated by Django 6.0.1 on 2026-01-23 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usereducation",
            name="gpa",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Grade Point Average (0.0 - 10.0 scale)",
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="usereducation",
            name="gpa_scale",
            field=models.DecimalField(
                decimal_places=1,
                default=10.0,
                help_text="GPA scale (e.g., 4.0, 5.0, 10.0)",
                max_digits=4,
            ),
        ),
    ]
