# Generated by Django 6.0.1 on 2026-01-15 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('career', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='careercomparison',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_comparisons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='careermarkettrend',
            index=models.Index(fields=['trend_type', '-data_date'], name='career_mark_trend_t_fb49d4_idx'),
        ),
        migrations.AddIndex(
            model_name='careermarkettrend',
            index=models.Index(fields=['direction', '-change_percentage'], name='career_mark_directi_3f0175_idx'),
        ),
        migrations.AddIndex(
            model_name='careermarkettrend',
            index=models.Index(fields=['industry'], name='career_mark_industr_4bcc0b_idx'),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='next_paths',
            field=models.ManyToManyField(blank=True, help_text='Potential next career paths', related_name='previous_paths', to='career.careerpath'),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='parent_path',
            field=models.ForeignKey(blank=True, help_text='Previous career path leading to this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_paths', to='career.careerpath'),
        ),
        migrations.AddField(
            model_name='careercomparison',
            name='careers',
            field=models.ManyToManyField(related_name='comparisons', to='career.careerpath'),
        ),
        migrations.AddField(
            model_name='careercomparison',
            name='recommended_career',
            field=models.ForeignKey(blank=True, help_text='Recommended career from comparison', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_in_comparisons', to='career.careerpath'),
        ),
        migrations.AddField(
            model_name='careerprediction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_predictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercareerbookmark',
            name='career_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='career.careerpath'),
        ),
        migrations.AddField(
            model_name='usercareerbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercareergoal',
            name='target_career',
            field=models.ForeignKey(blank=True, help_text='Target career path', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_goals', to='career.careerpath'),
        ),
        migrations.AddField(
            model_name='usercareergoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='careerpath',
            index=models.Index(fields=['industry', 'career_level'], name='career_path_industr_81e0e4_idx'),
        ),
        migrations.AddIndex(
            model_name='careerpath',
            index=models.Index(fields=['-demand_score'], name='career_path_demand__fd5d13_idx'),
        ),
        migrations.AddIndex(
            model_name='careerpath',
            index=models.Index(fields=['-popularity_score'], name='career_path_popular_f5ef7e_idx'),
        ),
        migrations.AddIndex(
            model_name='careerprediction',
            index=models.Index(fields=['user', '-created_at'], name='career_pred_user_id_44479a_idx'),
        ),
        migrations.AddIndex(
            model_name='careerprediction',
            index=models.Index(fields=['status'], name='career_pred_status_a94570_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercareerbookmark',
            unique_together={('user', 'career_path')},
        ),
        migrations.AddIndex(
            model_name='usercareergoal',
            index=models.Index(fields=['user', 'status'], name='user_career_user_id_e893a5_idx'),
        ),
        migrations.AddIndex(
            model_name='usercareergoal',
            index=models.Index(fields=['target_date'], name='user_career_target__5aaf13_idx'),
        ),
    ]
