# Generated by Django 6.0.1 on 2026-01-15 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('career', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='careeranalytics',
            name='career_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics', to='career.careerpath'),
        ),
        migrations.AddField(
            model_name='careeranalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewanalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobsearchanalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_search_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learninganalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermetrics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_name', 'timestamp'], name='analytics_a_event_n_ad6c50_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['user', 'timestamp'], name='analytics_a_user_id_5c8c13_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['session_id'], name='analytics_a_session_8757e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='careeranalytics',
            unique_together={('user', 'career_path')},
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'activity_type'], name='analytics_u_user_id_266824_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'created_at'], name='analytics_u_user_id_630f80_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['activity_type', 'created_at'], name='analytics_u_activit_2317fd_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['resource_type', 'resource_id'], name='analytics_u_resourc_f63bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='usermetrics',
            index=models.Index(fields=['user', 'date'], name='analytics_u_user_id_0f244f_idx'),
        ),
        migrations.AddIndex(
            model_name='usermetrics',
            index=models.Index(fields=['date'], name='analytics_u_date_64419a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermetrics',
            unique_together={('user', 'date')},
        ),
    ]
