# Generated by Django 6.0.1 on 2026-01-22 16:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("career", "0002_initial"),
        ("jobs", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewQuestion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("behavioral", "Behavioral"),
                            ("technical", "Technical"),
                            ("situational", "Situational"),
                            ("case_study", "Case Study"),
                            ("coding", "Coding"),
                            ("system_design", "System Design"),
                            ("brainteaser", "Brainteaser"),
                        ],
                        default="behavioral",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("companies", models.JSONField(blank=True, default=list)),
                ("expected_topics", models.JSONField(blank=True, default=list)),
                ("sample_answer", models.TextField(blank=True)),
                ("answer_tips", models.JSONField(blank=True, default=list)),
                ("situation_hint", models.TextField(blank=True)),
                ("task_hint", models.TextField(blank=True)),
                ("action_hint", models.TextField(blank=True)),
                ("result_hint", models.TextField(blank=True)),
                ("times_asked", models.PositiveIntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "career_paths",
                    models.ManyToManyField(
                        blank=True,
                        related_name="interview_questions",
                        to="career.careerpath",
                    ),
                ),
            ],
            options={
                "ordering": ["-times_asked", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewSchedule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("phone", "Phone Screen"),
                            ("video", "Video Call"),
                            ("onsite", "On-site"),
                            ("technical", "Technical Interview"),
                            ("behavioral", "Behavioral Interview"),
                            ("panel", "Panel Interview"),
                            ("final", "Final Interview"),
                        ],
                        default="video",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("round_number", models.PositiveIntegerField(default=1)),
                ("scheduled_at", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("location", models.CharField(blank=True, max_length=500)),
                ("meeting_link", models.URLField(blank=True)),
                ("interviewer_name", models.CharField(blank=True, max_length=200)),
                ("interviewer_title", models.CharField(blank=True, max_length=200)),
                ("preparation_notes", models.TextField(blank=True)),
                ("questions_to_ask", models.JSONField(blank=True, default=list)),
                ("feedback", models.TextField(blank=True)),
                (
                    "self_assessment",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_schedules",
                        to="jobs.jobapplication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("practice", "Practice"),
                            ("mock", "Mock Interview"),
                            ("ai_feedback", "AI Feedback Session"),
                        ],
                        default="practice",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("target_company", models.CharField(blank=True, max_length=200)),
                ("question_types", models.JSONField(blank=True, default=list)),
                (
                    "difficulty_preference",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("num_questions", models.PositiveIntegerField(default=5)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                ("overall_score", models.PositiveIntegerField(blank=True, null=True)),
                ("ai_feedback", models.TextField(blank=True)),
                ("strengths", models.JSONField(blank=True, default=list)),
                ("improvements", models.JSONField(blank=True, default=list)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "job_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interview_sessions",
                        to="jobs.jobapplication",
                    ),
                ),
                (
                    "target_career",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="career.careerpath",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewResponse",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("response_text", models.TextField(blank=True)),
                ("response_audio_url", models.URLField(blank=True)),
                ("response_video_url", models.URLField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("time_taken_seconds", models.PositiveIntegerField(default=0)),
                ("ai_score", models.PositiveIntegerField(blank=True, null=True)),
                ("ai_feedback", models.TextField(blank=True)),
                ("ai_analysis", models.JSONField(blank=True, default=dict)),
                ("content_score", models.PositiveIntegerField(blank=True, null=True)),
                ("structure_score", models.PositiveIntegerField(blank=True, null=True)),
                ("clarity_score", models.PositiveIntegerField(blank=True, null=True)),
                ("relevance_score", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "self_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("self_notes", models.TextField(blank=True)),
                ("is_flagged", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="interview.interviewquestion",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="interview.interviewsession",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "order"],
            },
        ),
        migrations.CreateModel(
            name="InterviewTip",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("preparation", "Preparation"),
                            ("during", "During Interview"),
                            ("follow_up", "Follow Up"),
                            ("body_language", "Body Language"),
                            ("communication", "Communication"),
                            ("technical", "Technical"),
                        ],
                        default="preparation",
                        max_length=20,
                    ),
                ),
                ("question_types", models.JSONField(blank=True, default=list)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "career_paths",
                    models.ManyToManyField(
                        blank=True,
                        related_name="interview_tips",
                        to="career.careerpath",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "order"],
            },
        ),
        migrations.CreateModel(
            name="UserInterviewPreference",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "preferred_question_types",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "preferred_difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("default_duration_minutes", models.PositiveIntegerField(default=30)),
                ("default_num_questions", models.PositiveIntegerField(default=5)),
                ("focus_skills", models.JSONField(blank=True, default=list)),
                ("weak_areas", models.JSONField(blank=True, default=list)),
                ("reminder_before_minutes", models.PositiveIntegerField(default=30)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User interview preferences",
            },
        ),
        migrations.AddIndex(
            model_name="interviewquestion",
            index=models.Index(
                fields=["question_type"], name="interview_i_questio_4f143f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interviewquestion",
            index=models.Index(
                fields=["difficulty"], name="interview_i_difficu_3dbc03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interviewquestion",
            index=models.Index(
                fields=["category"], name="interview_i_categor_edbdb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interviewschedule",
            index=models.Index(
                fields=["user", "status"], name="interview_i_user_id_031b70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interviewschedule",
            index=models.Index(
                fields=["scheduled_at"], name="interview_i_schedul_c5a53c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interviewsession",
            index=models.Index(
                fields=["user", "status"], name="interview_i_user_id_2ae641_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interviewsession",
            index=models.Index(
                fields=["session_type"], name="interview_i_session_32fc6b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="interviewresponse",
            unique_together={("session", "question")},
        ),
    ]
